#!/bin/bash

# The canonical way to update is through the update script below,
# but this file is here for backwards compatibility.

# Without this file, we have no way of giving users an update command
# that will work regardless of BasslineMnk version.

sudo /opt/basslinemnk-privileged/update
